acseo_typesense:
    # Typesense host settings
    typesense:
        url: '%env(resolve:TYPESENSE_URL)%'
        key: '%env(resolve:TYPESENSE_KEY)%'
        collection_prefix: 'cc_'

    # Collection settings
    collections:
        posts:                                     # Typesense collection name
            entity: 'App\Entity\Post'              # Doctrine Entity class
            fields:
                id:                                # Entity attribute name
                    name: id                       # Typesense attribute name
                    type: primary                  # Attribute type
                sortable_id:
                    entity_attribute: id             # Entity attribute name forced
                    name: sortable_id                # Typesense field name
                    type: int32
                title:
                    name: title
                    type: string
                content:
                    name: content
                    type: string
#                author:
#                    name: author
#                    type: object                    # Object conversion with __toString()
#                author.country:
#                    name: author_country
#                    type: string
#                    facet: true                      # Declare field as facet (required to use "group_by" query option)
#                    entity_attribute: author.country # Equivalent of $book->getAuthor()->getCountry()
#                genres:
#                    name: genres
#                    type: collection                 # Convert ArrayCollection to array of strings
#                publishedAt:
#                    name: publishedAt
#                    type: datetime
#                    optional: true                   # Declare field as optional
            default_sorting_field: sortable_id       # Default sorting field. Must be int32 or float
            symbols_to_index: ['+']                  # Optional - You can add + to this list to make the word c++ indexable verbatim.
#        users:
#            entity: App\Entity\User
#            fields:
#                id:
#                    name: id
#                    type: primary
#                sortable_id:
#                    entity_attribute: id
#                    name: sortable_id
#                    type: int32
#                email:
#                    name: email
#                    type: string
#            default_sorting_field: sortable_id
#            token_separators: ['+', '-', '@', '.']  # Optional - This will cause contact+docs-example@typesense.org to be indexed as contact, docs, example, typesense and org.