fm_elfinder:
    assets_path: /assets
    instances:
        default:
            locale: fr
            editor: ckeditor
            relative_path: false
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: [ 'image/png', 'image/jpg', 'image/jpeg' ]
                        upload_deny: [ 'all' ]
                        upload_max_size: 2M
                        attributes:
                            - { pattern: '/(.*?)/', read: true, write: true, locked: false }
