# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        post_config:
            language: fr
            toolbar: standard
            uiColor: "#e65c4f"
            width: "100%"
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
