vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        users:
            uri_prefix: /images/user/profile
            upload_destination: '%kernel.project_dir%/public/images/user/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false