version: '3'

services:
  ###> typesense/typesense-bundle ###
  typesense:
    image: typesense/typesense:0.24.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
###< typesense/typesense-bundle ###
